dist: trusty
os:  linux

language: cpp

compiler:
  - gcc

env:
  global:
    - BUILD_DEBUG=false

script:
  - CXX="g++ -m64" CC="gcc -m64" make UNICORN_STATIC=yes UNICORN_DYNAMIC=no UNICORN_DEBUG=$BUILD_DEBUG

